export enum TableName {
  CITY = 'city',
  COUNTRY = 'country',
  ADDRESS = 'address',
  USER = 'user',
  USER_DOCUMENT = 'user_document',
  VERIFICATION = 'verification',
  DEPOT = 'depot',
  DEPOT_STAFF = 'depot_staff',
  DEPOT_STAFF_ROLE = 'depot_staff_role',
  DEPOT_CARRIER = 'depot_carrier',
  ROUTE = 'route',
  GATE = 'gate',
  ROUTE_GATE = 'route_gate',
  SHIPPING = 'shipping',
  SHIPPING_EVENT = 'shipping_event',
  CARRIER = 'carrier',
  PARCEL = 'parcel',
  PARCEL_STATUS = 'parcel_status',
  PARCEL_GROUP = 'parcel_group',
  PARCEL_ITEM = 'parcel_item',
  BUYER_REQUEST = 'buyer_request',
  BUYER_REQUEST_ITEM = 'buyer_request_item',
}
